import { expect, test } from "bun:test";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const root = join(import.meta.dirname, ".."); const checker = join(root, "scripts", "verify-host-compat.ts");
const compiler = join(root, "node_modules", ".bin", "tsc");
const valid = `export type GitFileChange={readonly path:string;readonly status:"added"|"modified"|"deleted"|"renamed"|"copied"|"type-changed"|"unmerged"|"untracked";readonly previousPath?:string}; export type ProjectGitStatus={readonly state:"not-repository"}|{readonly state:"ready";readonly branch:string|null;readonly detached:boolean;readonly staged:readonly GitFileChange[];readonly unstaged:readonly GitFileChange[];readonly untracked:readonly GitFileChange[];readonly truncated:boolean}; export interface ExtensionViewContext {readonly signal:AbortSignal;readonly scope:{readonly installationId:string;readonly sessionId:string};readonly selection:{readonly selectedSessionId:string|null};readonly theme:Readonly<Record<string,string>>;readonly storage:{get(key:string):string|null;set(key:string,value:string):void;remove(key:string):void};readonly project:{gitStatus(signal?:AbortSignal):Promise<ProjectGitStatus>};readonly documents:{read(id:string):Promise<unknown|null>;subscribe(id:string,listener:(value:unknown|null,revision:number)=>void):()=>void}} export interface ContextViewContribution {readonly id:string;readonly title:string;mount(container:HTMLElement,context:ExtensionViewContext):{dispose():void;setVisible?(visible:boolean):void}} export interface ExtensionRegistrationHost {registerContextView(value:ContextViewContribution):void;registerTerminalLayout(value:{readonly id:string;readonly title:string;arrange(context:{readonly panes:readonly {readonly id:string}[];readonly selectedPaneId:string|null;readonly viewport:{readonly width:number;readonly height:number}}):{readonly version:1;readonly rows:readonly {readonly size:number}[];readonly columns:readonly {readonly size:number}[];readonly placements:readonly {readonly paneId:string;readonly row:number;readonly column:number;readonly rowSpan?:number;readonly columnSpan?:number}[]}}):void}`;
function run(source: string) { const stage = mkdtempSync(join(tmpdir(), "wolfpack-host-compat-")); try { const host = join(stage, "host", "src", "extensions"); mkdirSync(host, { recursive: true }); writeFileSync(join(host, "public-sdk.ts"), source); const result = Bun.spawnSync([process.execPath, checker], { cwd: stage, env: { ...process.env, HOME: join(stage, "home"), WOLFPACK_EXTENSION_HOST_ROOT: join(stage, "host") }, stdout: "pipe", stderr: "pipe" }); return { status: result.exitCode, output: result.stdout.toString() + result.stderr.toString() }; } finally { rmSync(stage, { recursive: true, force: true }); } }
test("host compatibility has pinned compiler, valid positive control, and causal export/signature negatives", () => {
  expect(existsSync(compiler), `missing pinned compiler ${compiler}`).toBe(true);
  expect(run(valid).status).toBe(0);
  const comments = run("// ExtensionRegistrationHost ExtensionViewContext ContextViewContribution ProjectGitStatus"); expect(comments.status).not.toBe(0); expect(comments.output).toContain("TS2306");
  const incompatible = run(valid.replace("readonly signal:AbortSignal", "readonly signal:string")); expect(incompatible.status).not.toBe(0); expect(incompatible.output).toContain("TS2344");
  expect(readFileSync(checker, "utf8")).toContain("strict APIv1 structural compatibility");
});
