#!/usr/bin/env bun
/** Explicit-host causal regressions for the real install checker (not a duplicate validator). */
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const mode = Bun.argv[2]; const checker = join(import.meta.dirname, "verify-host-install.ts");
if (mode) {
  const actual = Bun.spawnSync.bind(Bun); const observations: unknown[] = []; let ownedHome = "";
  Bun.spawnSync = ((cmd: string[] | { cmd: string[] }, options: { env: Record<string, string> }) => { const argv = Array.isArray(cmd) ? cmd : cmd.cmd; if (argv[1]?.endsWith("/src/cli/index.ts")) { const env = options.env, skills = env.WOLFPACK_PI_SKILLS_ROOT; ownedHome = env.HOME; observations.push({ argv: argv.slice(2), envKeys: Object.keys(env).sort() }); if (mode === "collision" && argv[3] === "install" && String(argv[4]).includes("unpacked-agent-context")) { const target = join(skills, "wolfpack-agent-context"); mkdirSync(target, { recursive: true }); writeFileSync(join(target, "SKILL.md"), "---\nname: wolfpack-agent-context\ndescription: collision\n---\nsentinel\n"); } if (mode === "modified" && argv[3] === "remove" && argv[4] === "agent-context") writeFileSync(join(skills, "wolfpack-agent-context", "SKILL.md"), "modified owned sentinel"); const altered = mode === "retain" && argv[3] === "remove" && argv[4] === "changes" ? [...argv.slice(0, 3), "disable", "changes"] : argv; let result = actual(altered, options); if (mode === "retain" && argv[3] === "remove" && argv[4] === "changes" && result.exitCode === 0) { const receipt = JSON.parse(result.stdout.toString()); result = { ...result, stdout: Buffer.from(JSON.stringify({ ...receipt, skills: [] })) }; } if (result.exitCode === 0 && (mode === "duplicate-install" || mode === "duplicate-remove")) { const receipt = JSON.parse(result.stdout.toString()); if ((mode === "duplicate-install" && argv[3] === "install" && String(argv[4]).includes("agent-context")) || (mode === "duplicate-remove" && argv[3] === "remove" && argv[4] === "agent-context")) { receipt.skills.push({ name: "wolfpack-agent-context", status: mode === "duplicate-install" ? "collision" : "modified" }); return { ...result, stdout: Buffer.from(JSON.stringify(receipt)) }; } } return result; } return actual(argv, options); }) as typeof Bun.spawnSync;
  let error: unknown; let failed = false; try { await import(`${checker}?mode=${mode}`); } catch (value) { failed = true; error = value; } console.log(JSON.stringify({ error: error instanceof Error ? error.message : error ? String(error) : "", cleaned: !!ownedHome && !existsSync(ownedHome), observations })); process.exit(failed ? 1 : 0);
}
const host = process.env.WOLFPACK_EXTENSION_HOST_ROOT; if (!host) throw new Error("set WOLFPACK_EXTENSION_HOST_ROOT to a selected host");
for (const expected of [{ mode: "positive", exit: 0, cause: "" }, { mode: "collision", exit: 1, cause: "not installed" }, { mode: "modified", exit: 1, cause: "not removed" }, { mode: "duplicate-install", exit: 1, cause: "exactly one" }, { mode: "duplicate-remove", exit: 1, cause: "exactly one" }, { mode: "retain", exit: 1, cause: "final catalog" }]) { const root = mkdtempSync(join(tmpdir(), "wolfpack-install-causal-")); try { const ambient = join(root, "ambient-skills"), home = join(root, "outer-home"), machine = join(root, "machine"), tasks = join(root, "tasks"); for (const path of [ambient, home, join(root, "tmp")]) mkdirSync(path, { recursive: true }); writeFileSync(join(ambient, "sentinel"), "unchanged"); writeFileSync(machine, "11111111-1111-4111-8111-111111111111\n"); const result = Bun.spawnSync(["bun", import.meta.path, expected.mode], { env: { PATH: process.env.PATH ?? "", SHELL: "/bin/sh", HOME: home, TMPDIR: join(root, "tmp"), WOLFPACK_EXTENSION_HOST_ROOT: host, WOLFPACK_PI_SKILLS_ROOT: ambient, WOLFPACK_MACHINE_ID_PATH: machine, WOLFPACK_TASK_ROOT: tasks, WOLFPACK_SETTINGS_PATH: join(root, "settings"), WOLFPACK_TASK_RELAY_ROOT: join(root, "relay") }, stdout: "pipe", stderr: "pipe" }); const receipt = JSON.parse(result.stdout.toString().trim().split("\n").at(-1)!); if (result.exitCode !== expected.exit || !receipt.cleaned || (expected.cause && !receipt.error.includes(expected.cause)) || readFileSync(join(ambient, "sentinel"), "utf8") !== "unchanged" || existsSync(join(ambient, "wolfpack-agent-context")) || existsSync(tasks)) throw new Error(`${expected.mode} did not produce the required causal result: ${result.stdout}${result.stderr}`); } finally { rmSync(root, { recursive: true, force: true }); } }
process.stdout.write("real checker causal positive, collision, modified, duplicate-receipt and retained-catalog controls passed\n");
