#!/usr/bin/env bun
/** Optional APIv1 proof: reviewed archives, owned paths, structured install/remove receipts. */
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const host = process.env.WOLFPACK_EXTENSION_HOST_ROOT;
if (!host) throw new Error("set WOLFPACK_EXTENSION_HOST_ROOT to an explicitly selected APIv1 host checkout");
const cli = join(host, "src", "cli", "index.ts"), stage = mkdtempSync(join(tmpdir(), "wolfpack-extensions-host-install-"));
const names = ["changes", "agent-context", "notes"] as const;
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("expected structured JSON object"); return value as Record<string, unknown>; }
function owned(root: string, value: string): void { if (!value.startsWith(`${root}/`)) throw new Error(`verification path escapes owned HOME: ${value}`); }
function exactSkillResult(value: unknown, status: "installed" | "removed"): void { if (!Array.isArray(value) || value.length !== 1) throw new Error(`Agent Context skill ${status} receipt must contain exactly one result`); const result = object(value[0]); if (result.name !== "wolfpack-agent-context" || result.status !== status) throw new Error(`Agent Context skill was not ${status}`); }
function noSkills(value: unknown, name: string): void { if (!Array.isArray(value) || value.length !== 0) throw new Error(`${name} unexpectedly returned skill deployment results`); }
try {
  const home = join(stage, "home"), skillsRoot = join(home, ".pi", "agent", "skills"); mkdirSync(skillsRoot, { recursive: true });
  const env = { PATH: process.env.PATH ?? "", SHELL: process.env.SHELL ?? "/bin/sh", HOME: home, TMPDIR: join(stage, "tmp"), WOLFPACK_PI_SKILLS_ROOT: skillsRoot, npm_config_cache: join(stage, "cache"), npm_config_userconfig: join(stage, "npmrc"), npm_config_ignore_scripts: "true" };
  owned(home, skillsRoot);
  const run = (args: string[]) => { const result = Bun.spawnSync(["bun", cli, ...args], { cwd: stage, env, stdin: "ignore", stdout: "pipe", stderr: "pipe" }); if (result.exitCode !== 0) throw new Error(`${args.join(" ")} failed: ${result.stderr.toString() || result.stdout.toString()}`); return object(JSON.parse(result.stdout.toString())); };
  const unpacked = new Map<string, string>();
  for (const name of names) { const packageRoot = join(import.meta.dirname, "..", "packages", name), manifest = object(JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8"))); if (typeof manifest.name !== "string" || typeof manifest.version !== "string") throw new Error(`invalid ${name} manifest`); const archive = join(packageRoot, `${manifest.name}-${manifest.version}.tgz`); if (!existsSync(archive)) throw new Error(`missing reviewed archive ${archive}`); const destination = join(stage, `unpacked-${name}`); mkdirSync(destination); if (Bun.spawnSync(["tar", "-xzf", archive, "-C", destination]).exitCode !== 0) throw new Error(`cannot unpack ${archive}`); unpacked.set(name, join(destination, "package")); const receipt = run(["extensions", "install", unpacked.get(name)!, "--trust-browser-code", ...(name === "agent-context" ? ["--skills", "pi"] : [])]); const installation = object(receipt.installation); const pkg = object(installation.package); if (installation.extensionId !== name || pkg.name !== manifest.name || pkg.version !== manifest.version) throw new Error(`install receipt mismatch for ${name}`); if (name === "agent-context") { exactSkillResult(receipt.skills, "installed"); const deployed = join(skillsRoot, "wolfpack-agent-context"); for (const path of ["SKILL.md", "references/context-format.md"]) if (!readFileSync(join(deployed, path)).equals(readFileSync(join(unpacked.get(name)!, "skills", "wolfpack-agent-context", path)))) throw new Error(`deployed Agent Context ${path} differs from reviewed archive`); } else noSkills(receipt.skills, name); }
  const listed = run(["extensions", "list", "--json"]), installations = listed.installations; if (!Array.isArray(installations)) throw new Error("list omitted installations"); const entries = installations.map(object); for (const name of names) { const entry = entries.find(value => value.extensionId === name); const manifest = object(JSON.parse(readFileSync(join(import.meta.dirname, "..", "packages", name, "package.json"), "utf8"))); if (!entry || entry.enabled !== true || object(entry.package).name !== manifest.name || object(entry.package).version !== manifest.version || object(entry.ui).path !== object(manifest.wolfpack).ui) throw new Error(`list package/UI receipt mismatch for ${name}`); } const agent = entries.find(value => value.extensionId === "agent-context"); if (!agent || !Array.isArray(agent.documents) || agent.documents.length !== 1 || object(agent.documents[0]).id !== "context" || object(agent.documents[0]).schemaVersion !== 1) throw new Error("list omitted Agent Context schema receipt");
  for (const name of names) { const removal = run(["extensions", "remove", name, ...(name === "agent-context" ? ["--skills-root", skillsRoot] : [])]); if (name === "agent-context") { exactSkillResult(removal.skills, "removed"); if (existsSync(join(skillsRoot, "wolfpack-agent-context"))) throw new Error("owned Agent Context skill remains after removal"); } else noSkills(removal.skills, name); }
  const finalList = run(["extensions", "list", "--json"]); if (!Array.isArray(finalList.installations) || finalList.installations.length !== 0) throw new Error("removed extensions remain in final catalog");
  process.stdout.write("isolated APIv1 archive-directory install/list/remove validated package/UI/schema and owned Agent Context skill deployment/removal\n");
} finally { rmSync(stage, { recursive: true, force: true }); }
